In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()

In [2]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(iris.data, iris.target, test_size=0.2)

In [15]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression(max_iter=1000)
log.fit(X_train,y_train)
log.score(X_test,y_test)

0.9666666666666667

In [16]:
from sklearn.tree import DecisionTreeClassifier
dec=DecisionTreeClassifier()
dec.fit(X_train,y_train)
dec.score(X_test,y_test)

0.9666666666666667

In [17]:
from sklearn.ensemble import RandomForestClassifier
rand=RandomForestClassifier(n_estimators=40)
rand.fit(X_train,y_train)
rand.score(X_test,y_test)

0.9666666666666667

In [18]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

0.9666666666666667

In [30]:
from sklearn.model_selection import cross_val_score
score_log=cross_val_score(LogisticRegression(max_iter=10000),iris.data,iris.target, cv=3)
score_log

array([0.98, 0.96, 0.98])

In [31]:
score_dec=cross_val_score(DecisionTreeClassifier(),iris.data, iris.target,cv=3)
score_dec

array([0.98, 0.92, 0.96])

In [32]:
score_rand=cross_val_score(RandomForestClassifier(n_estimators=20),iris.data, iris.target,cv=3)
score_rand

array([0.98, 0.92, 0.96])

In [33]:
score_svc=cross_val_score(SVC(),iris.data, iris.target,cv=3)
score_svc

array([0.96, 0.98, 0.94])

In [34]:
np.average(score_log)

0.9733333333333333

In [35]:
np.average(score_dec)

0.9533333333333333

In [36]:
np.average(score_rand)

0.9533333333333333

In [37]:
np.average(score_svc)

0.96